cc_binary(
    name = "thread1",
    srcs = ["thread1.cc"],
)

cc_binary(
    name = "thread2",
    srcs = ["thread2.cc"],
)

cc_binary(
    name = "download",
    srcs = ["download.cc"],
    # copts = [
    #     "-std=c++2a",
    # ],
)
