cc_binary(
    name = "rnn_ops_test",
    srcs = ["rnn_ops_test.cc"],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "rnn_ops_restore",
    srcs = ["rnn_ops_restore.cc"],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "rnn_ops_restore_by_clientsession",
    srcs = ["rnn_ops_restore_by_clientsession.cc"],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "lstm_ops_test",
    srcs = [
        "lstm_ops_test.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "lstm_multi_layers",
    srcs = [
        "lstm_multi_layers.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "lstm_multi_layers_autograd",
    srcs = [
        "lstm_multi_layers_autograd.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)
