/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ps_proxy_thrift_constants.h"



const ps_proxy_thriftConstants g_ps_proxy_thrift_constants;

ps_proxy_thriftConstants::ps_proxy_thriftConstants() {
}



