package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@com_github_fmtlib_fmt//:fmt",
    ],
)
