/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef my_server_CONSTANTS_H
#define my_server_CONSTANTS_H

#include "my_server_types.h"



class my_serverConstants {
 public:
  my_serverConstants();

};

extern const my_serverConstants g_my_server_constants;



#endif
