cc_binary(
    name = "hello",
    srcs = [
        "hello-world.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "stringjoin-ops",
    srcs = [
        "stringjoin-ops.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "naming_ops",
    srcs = [
        "naming-ops.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "basic_tensors",
    srcs = [
        "basic-tensors.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "basic_operations",
    srcs = [
        "basic-operations.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "basic_io",
    srcs = [
        "basic-io.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "basic_graphdef",
    srcs = [
        "basic-graphdef.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "tfrecord_test",
    srcs = [
        "tfrecord_test.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "tfrecord_test2",
    srcs = [
        "tfrecord_test2.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)

cc_binary(
    name = "generatordataset_test",
    srcs = [
        "generatordataset_test.cc",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@com_github_gflags_gflags//:gflags",
        "@cppbuilt_lib//Tensorflow:tensorflow_cc",
        "@cppbuilt_lib//Tensorflow:tensorflow_framework",
    ],
)
