workspace(name = "tf_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "tensorflow",
    branch = "r2.4",
    remote = "https://fuhailin:Feige001gitee@gitee.com/fuhailin/tensorflow_bazel.git",
)

# This com_google_protobuf repository is required for proto_library rule.
# It provides the protocol compiler binary (i.e., protoc).
#
# We declare it as local_repository so we can test changes
# before they get merged. You'll want to use the following instead:
#
http_archive(
    name = "com_google_protobuf",
    strip_prefix = "protobuf-3.9.2",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v3.9.2.zip",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
