android_binary(
    name = "greeter_app",
    manifest = "AndroidManifest.xml",
    visibility = ["//myexamples/android_instrumentation_test/src/test:__subpackages__"],
    deps = ["//myexamples/android_instrumentation_test/src/main/java/com/example/bazel:greeter_activity"],
)
