# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
# http_archive(
#     name = "com_github_jupp0r_prometheus_cpp",
#     strip_prefix = "prometheus-cpp-master",
#     urls = ["https://github.com/jupp0r/prometheus-cpp/archive/master.zip"],
# )

# load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cpp_repositories")

# prometheus_cpp_repositories()
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
http_archive(
    name = "com_github_jupp0r_prometheus_cpp",
    strip_prefix = "prometheus-cpp-0.9.0",
    urls = ["https://github.com/jupp0r/prometheus-cpp/archive/v0.9.0.zip"],
)

load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cpp_repositories")

prometheus_cpp_repositories()
