FROM continuumio/miniconda3:latest
# ENV PATH="/root/miniconda3/bin:${PATH}"
# ARG PATH="/root/miniconda3/bin:${PATH}"

# ADD sources.list /etc/apt/
RUN apt-get update && apt-get install -y \
      wget \
      git \
      aria2 \
      curl \
      vim \
      cmake \
      && rm -rf /var/lib/apt/lists/*
RUN wget \
      https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh \
      && mkdir /root/.conda \
      && bash Miniconda3-latest-Linux-x86_64.sh -b \
      && rm -f Miniconda3-latest-Linux-x86_64.sh 
RUN conda --version
RUN git clone https://github.com.cnpmjs.org/tensorflow/tensorflow.git --depth=1 --branch=r2.4