package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "leveldb_test",
    srcs = [
        "leveldb_test.cc",
    ],
    deps = [
        "@com_github_google_leveldb//:leveldb",
    ],
)
