package(default_visibility = ["//visibility:public"])

_COPTS = [
    "-std=gnu++2a",
]

cc_library(
    name = "ListNode",
    hdrs = [
        "ListNode.h",
    ],
    copts = _COPTS,
)

cc_library(
    name = "TreeNode",
    hdrs = [
        "TreeNode.h",
    ],
    copts = _COPTS,
)
