workspace(name = "foo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Group the sources of the library so that CMake rule have access to it
all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

http_archive(
    name = "rules_foreign_cc",
    strip_prefix = "rules_foreign_cc-master",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

# Eigen source code repository
http_archive(
    name = "eigen",
    build_file_content = all_content,
    strip_prefix = "eigen-3.3.9",
    urls = [
        "https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz",
    ],
)

# OpenBLAS source code repository
http_archive(
    name = "openblas",
    build_file_content = all_content,
    strip_prefix = "OpenBLAS-0.3.2",
    urls = ["https://github.com/xianyi/OpenBLAS/archive/v0.3.2.tar.gz"],
)
