cc_binary(
    name = "auto_ptr",
    srcs = ["auto_ptr.cc"],
    # deps = [
    #     "@com_github_google_glog//:glog",
    # ],
    # copts = [
    #     "-std=c++14",
    # ],
)

cc_binary(
    name = "unique_ptr",
    srcs = ["unique_ptr.cc"],
)

cc_binary(
    name = "shared_ptr",
    srcs = ["shared_ptr.cc"],
)

cc_binary(
    name = "weak_ptr",
    srcs = ["weak_ptr.cc"],
)
