# In main/BUILD
load("//:clang_format.bzl", "clang_formatted_cc_binary")

# In main/BUILD
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

clang_formatted_cc_binary(
    name = "hello-world1",
    srcs = ["hello-world.cc"],
)