cc_binary(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    # copts = [
    #     "-std=c++14",
    # ],
)

cc_binary(
    name = "test1",
    srcs = ["test_map_access.cc"],
)
