cc_library(
    name = "ParaServThrift_lib",
    srcs = [
        "ParaServ.cpp",
        "para_serv_constants.cpp",
        "para_serv_types.cpp",
    ],
    hdrs = [
        "ParaServ.h",
        "para_serv_constants.h",
        "para_serv_types.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@apache_thrift//:thrift",
    ],
)
