/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "para_serv_constants.h"

namespace ps {

const para_servConstants g_para_serv_constants;

para_servConstants::para_servConstants() {
}

} // namespace

