/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef para_serv_CONSTANTS_H
#define para_serv_CONSTANTS_H

#include "para_serv_types.h"

namespace ps {

class para_servConstants {
 public:
  para_servConstants();

};

extern const para_servConstants g_para_serv_constants;

} // namespace

#endif
