cc_binary(
    name = "example",
    srcs = ["example.cpp"],
    deps = [
        "//cxxtimer",
    ],
)

cc_binary(
    name = "zlib_usage_example",
    srcs = ["zlib-example.cpp"],
    deps = ["@zlib"],
)