/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "scan_data_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace hulk {


ScanData::~ScanData() throw() {
}


void ScanData::__set_RespData(const std::map<std::string, std::string> & val) {
  this->RespData = val;
}

void ScanData::__set_IsEnd(const bool val) {
  this->IsEnd = val;
}

void ScanData::__set_cursor(const std::string& val) {
  this->cursor = val;
}
std::ostream& operator<<(std::ostream& out, const ScanData& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ScanData::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->RespData.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              std::string& _val6 = this->RespData[_key5];
              xfer += iprot->readString(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.RespData = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->IsEnd);
          this->__isset.IsEnd = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->cursor);
          this->__isset.cursor = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ScanData::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ScanData");

  xfer += oprot->writeFieldBegin("RespData", ::apache::thrift::protocol::T_MAP, 1);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->RespData.size()));
    std::map<std::string, std::string> ::const_iterator _iter7;
    for (_iter7 = this->RespData.begin(); _iter7 != this->RespData.end(); ++_iter7)
    {
      xfer += oprot->writeString(_iter7->first);
      xfer += oprot->writeString(_iter7->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("IsEnd", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->IsEnd);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("cursor", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->cursor);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ScanData &a, ScanData &b) {
  using ::std::swap;
  swap(a.RespData, b.RespData);
  swap(a.IsEnd, b.IsEnd);
  swap(a.cursor, b.cursor);
  swap(a.__isset, b.__isset);
}

ScanData::ScanData(const ScanData& other8) {
  RespData = other8.RespData;
  IsEnd = other8.IsEnd;
  cursor = other8.cursor;
  __isset = other8.__isset;
}
ScanData& ScanData::operator=(const ScanData& other9) {
  RespData = other9.RespData;
  IsEnd = other9.IsEnd;
  cursor = other9.cursor;
  __isset = other9.__isset;
  return *this;
}
void ScanData::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ScanData(";
  out << "RespData=" << to_string(RespData);
  out << ", " << "IsEnd=" << to_string(IsEnd);
  out << ", " << "cursor=" << to_string(cursor);
  out << ")";
}

} // namespace
