load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "test1",
    srcs = ["test1.cpp"],
    deps = [
        "@eigen",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@eigen",
    ],
)

cc_binary(
    name = "test",
    srcs = ["test.cpp"],
    deps = [
        "@eigen",
    ],
)
