workspace(name = "cc_third_party")

load("//bazel:repositories.bzl", "repositories")

repositories()

# Don't use preinstalled tools to ensure builds are as hermetic as possible
load("//bazel:deps_imports.bzl", "dependency_imports")

dependency_imports()

# load("//third_party/grpc:grpc_deps.bzl", "load_grpc_deps")
# load_grpc_deps()

# load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

# rules_proto_dependencies()
# rules_proto_toolchains()

# load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps", "grpc_test_only_deps")

# grpc_deps()
# grpc_test_only_deps()

# load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

# grpc_extra_deps()

# load("@com_github_brpc//:bazel/brpc.bzl", "brpc_proto_library")
# brpc_proto_library()

# load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
# rules_java_dependencies()
# rules_java_toolchains()
