/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hulk_proxy_CONSTANTS_H
#define hulk_proxy_CONSTANTS_H

#include "hulk_proxy_types.h"

namespace hulk {

class hulk_proxyConstants {
 public:
  hulk_proxyConstants();

};

extern const hulk_proxyConstants g_hulk_proxy_constants;

} // namespace

#endif
