/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hulk_proxy_constants.h"

namespace hulk {

const hulk_proxyConstants g_hulk_proxy_constants;

hulk_proxyConstants::hulk_proxyConstants() {
}

} // namespace

