/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef scan_data_CONSTANTS_H
#define scan_data_CONSTANTS_H

#include "scan_data_types.h"

namespace hulk {

class scan_dataConstants {
 public:
  scan_dataConstants();

};

extern const scan_dataConstants g_scan_data_constants;

} // namespace

#endif
