/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Greeter_H
#define Greeter_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "benchmark_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GreeterIf {
 public:
  virtual ~GreeterIf() {}
  virtual void say(BenchmarkMessage& _return, const BenchmarkMessage& name) = 0;
};

class GreeterIfFactory {
 public:
  typedef GreeterIf Handler;

  virtual ~GreeterIfFactory() {}

  virtual GreeterIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GreeterIf* /* handler */) = 0;
};

class GreeterIfSingletonFactory : virtual public GreeterIfFactory {
 public:
  GreeterIfSingletonFactory(const ::std::shared_ptr<GreeterIf>& iface) : iface_(iface) {}
  virtual ~GreeterIfSingletonFactory() {}

  virtual GreeterIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(GreeterIf* /* handler */) {}

 protected:
  ::std::shared_ptr<GreeterIf> iface_;
};

class GreeterNull : virtual public GreeterIf {
 public:
  virtual ~GreeterNull() {}
  void say(BenchmarkMessage& /* _return */, const BenchmarkMessage& /* name */) {
    return;
  }
};

typedef struct _Greeter_say_args__isset {
  _Greeter_say_args__isset() : name(false) {}
  bool name :1;
} _Greeter_say_args__isset;

class Greeter_say_args {
 public:

  Greeter_say_args(const Greeter_say_args&);
  Greeter_say_args& operator=(const Greeter_say_args&);
  Greeter_say_args() {
  }

  virtual ~Greeter_say_args() noexcept;
  BenchmarkMessage name;

  _Greeter_say_args__isset __isset;

  void __set_name(const BenchmarkMessage& val);

  bool operator == (const Greeter_say_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Greeter_say_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Greeter_say_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Greeter_say_pargs {
 public:


  virtual ~Greeter_say_pargs() noexcept;
  const BenchmarkMessage* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Greeter_say_result__isset {
  _Greeter_say_result__isset() : success(false) {}
  bool success :1;
} _Greeter_say_result__isset;

class Greeter_say_result {
 public:

  Greeter_say_result(const Greeter_say_result&);
  Greeter_say_result& operator=(const Greeter_say_result&);
  Greeter_say_result() {
  }

  virtual ~Greeter_say_result() noexcept;
  BenchmarkMessage success;

  _Greeter_say_result__isset __isset;

  void __set_success(const BenchmarkMessage& val);

  bool operator == (const Greeter_say_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Greeter_say_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Greeter_say_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Greeter_say_presult__isset {
  _Greeter_say_presult__isset() : success(false) {}
  bool success :1;
} _Greeter_say_presult__isset;

class Greeter_say_presult {
 public:


  virtual ~Greeter_say_presult() noexcept;
  BenchmarkMessage* success;

  _Greeter_say_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GreeterClient : virtual public GreeterIf {
 public:
  GreeterClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GreeterClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void say(BenchmarkMessage& _return, const BenchmarkMessage& name);
  void send_say(const BenchmarkMessage& name);
  void recv_say(BenchmarkMessage& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GreeterProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<GreeterIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (GreeterProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_say(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GreeterProcessor(::std::shared_ptr<GreeterIf> iface) :
    iface_(iface) {
    processMap_["say"] = &GreeterProcessor::process_say;
  }

  virtual ~GreeterProcessor() {}
};

class GreeterProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GreeterProcessorFactory(const ::std::shared_ptr< GreeterIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< GreeterIfFactory > handlerFactory_;
};

class GreeterMultiface : virtual public GreeterIf {
 public:
  GreeterMultiface(std::vector<std::shared_ptr<GreeterIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GreeterMultiface() {}
 protected:
  std::vector<std::shared_ptr<GreeterIf> > ifaces_;
  GreeterMultiface() {}
  void add(::std::shared_ptr<GreeterIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void say(BenchmarkMessage& _return, const BenchmarkMessage& name) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->say(_return, name);
    }
    ifaces_[i]->say(_return, name);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GreeterConcurrentClient : virtual public GreeterIf {
 public:
  GreeterConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  GreeterConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void say(BenchmarkMessage& _return, const BenchmarkMessage& name);
  int32_t send_say(const BenchmarkMessage& name);
  void recv_say(BenchmarkMessage& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
