cc_test(
    name = "client",
    srcs = [
        "lr_ps.cc",
    ],
    deps = [
        "@pslite",
    ],
)

cc_test(
    name = "server",
    srcs = [
        "ps.cpp",
    ],
    deps = [
        "@pslite",
    ],
)
