cc_binary(
    name = "example",
    srcs = ["TestCase.cpp"],
    copts = [
        "-std=c++17",
    ],
    deps = [
        "@com_github_catchorg_Catch2//:catch2",
        # "@com_github_catchorg_Catch2//:catch2_main",
    ],
)
