load("//thrift:thrift.bzl", "thrift_cc_library")

thrift_cc_library(
    name = "thrift_lib",
    srcs = ["a.thrift"],
    visibility = ["//visibility:public"],
)

# thrift_java_library(
#   name="a-thrift-java-lib",
#   thrift_library="a-thrift-lib",
#   visibility=["//visibility:public"],
# )

# thrift_library(
#   name="b-thrift-lib",
#   srcs=["b.thrift"],
#   visibility=["//visibility:public"],
# )
