cc_binary(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "//bits:stdcxx",
        "//include:LinkedList",
        "@com_github_google_glog//:glog",
        "@com_google_googletest//:gtest_main",
    ],
)
