cc_binary(
    name = "rand",
    srcs = ["rand_test.cc"],
    # copts = [
    #     "-std=c++14",
    # ],
)

cc_binary(
    name = "srand",
    srcs = ["srand_test.cc"],
    # copts = [
    #     "-std=c++14",
    # ],
)
