/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "galaxy_predict_constants.h"



const galaxy_predictConstants g_galaxy_predict_constants;

galaxy_predictConstants::galaxy_predictConstants() {
}



