cc_binary(
    name = "condition_variable",
    srcs = ["test_condition_variable.cc"],
    # deps = [
    #     "@com_github_google_glog//:glog",
    # ],
    # copts = [
    #     "-std=c++14",
    # ],
)

cc_binary(
    name = "bug",
    srcs = ["test_bug.cc"],
)
