load("//:clang_format.bzl", "clang_formatted_cc_binary")

clang_formatted_cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

# cc_binary(
#     name = "hello-world",
#     srcs = ["hello-world.cc"],
# )