workspace(name = "org_iceboy_trunk")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
# load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#     name = 'com_github_google_flatbuffers',
#     urls = ['https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz'],
#     # sha256 = '20a400e940634108bad812f571582eeffc728eac',
#     # strip_prefix = 'flatbuffers-1.9.0',
#     # build_file = 'BUILD',
# )

git_repository(
    name = "com_github_google_flatbuffers",
    commit = "6df40a2471737b27271bdd9b900ab5f3aec746c7",
    remote = "https://github.com/google/flatbuffers.git",
)
