package(default_visibility = ["//visibility:public"])

_COPTS = [
    "-std=gnu++2a",
]

cc_library(
    name = "LinkedList",
    srcs = [
        "LinkedList.cpp",
    ],
    hdrs = [
        "LinkedList.h",
    ],
    copts = _COPTS,
    # strip_include_prefix = "include",
)

cc_library(
    name = "TreeNode",
    hdrs = [
        "TreeNode.h",
    ],
    copts = _COPTS,
)
