cc_test(
    name = "rocketdb",
    srcs = [
        "test_rocketdb.cc",
    ],
    deps = [
        "@com_github_facebook_rocksdb//:rocksdb",
    ],
)

cc_test(
    name = "rocksdb",
    srcs = [
        "multi_processes_example.cc",
    ],
    deps = [
        "@com_github_facebook_rocksdb//:rocksdb",
    ],
)
