cc_binary(
    name = "main1",
    srcs = ["compute_register_example.cc"],
    deps = [
        "@apache_arrow//:arrow",
    ],
)

cc_binary(
    name = "write",
    srcs = ["write_parquet.cc"],
    deps = [
        # "@apache_arrow//:arrow",
    ],
)
