cc_binary(
    name = "gmock_leak_test_",
    testonly = 1,
    srcs = ["gmock_leak_test_.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_binary(
    name = "googletest-shuffle-test_",
    srcs = ["googletest-shuffle-test_.cc"],
    deps = [
        "@com_google_googletest//:gtest",
    ],
)
