/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ps_proxy_thrift_CONSTANTS_H
#define ps_proxy_thrift_CONSTANTS_H

#include "ps_proxy_thrift_types.h"



class ps_proxy_thriftConstants {
 public:
  ps_proxy_thriftConstants();

};

extern const ps_proxy_thriftConstants g_ps_proxy_thrift_constants;



#endif
