load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "hello-world",
    srcs = ["prometheus_test.cpp"],
    deps = [
        # "@com_github_jupp0r_prometheus_cpp//pull"
        "@com_github_jupp0r_prometheus_cpp//push",
        ],
)