cc_binary(
    name = "cat",
    srcs = [
        "CatDogCNN.cpp",
        "CatDogCNN.h",
        "main.cpp",
    ],
    copts = [
        "-std=c++14",
    ],
    deps = [
        "@cpp3rd_lib//tensorflow:tensorflow_cc",
        "@cpp3rd_lib//tensorflow:tensorflow_framework",
    ],
)
